development:
  adapter: postgresql
  encoding: utf8
  database: rednews_dev
  username: rich_user
  password:
  host: localhost
test:
  adapter: postgresql
  encoding: utf8
  database: rednews_test
  username: rich_user
  password:
  host: localhost
production:
  pool: <%= ENV['MAX_THREADS'] %>
  timeout: 10000
